package com.workhub.saasbackend.entity;

public enum AuditEventType {
    AUTH_LOGIN_SUCCESS,
    AUTH_LOGIN_FAILURE,
    AUTH_ACCESS_DENIED,
    PROJECT_CREATED,
    PROJECT_DELETED,
    PROJECT_TX_ROLLBACK,
    PROJECT_SAGA_STARTED,
    PROJECT_SAGA_COMPLETED,
    PROJECT_SAGA_COMPENSATED,
    TASK_CREATED,
    TASK_STATUS_CHANGED,
    WORKSPACE_CREATED,
    WORKSPACE_READ,
    JOB_CREATED,
    JOB_PUBLISH_FAILED,
    JOB_PROCESSING,
    JOB_COMPLETED,
    JOB_FAILED,
    CROSS_TENANT_DENIED,
    QUOTA_EXCEEDED,
    ADMIN_ACTION
}
